### ISSUE TITLE
Macroplay needs to take a move

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-connect-three#17]
https://github.com/TU-CSCI2322-FL22/solver-connect-three/blob/3b398642bada87d610c043c993389cc52d8ec5ec/Main.hs#L83

- I would call this `makeMove :: MacroGame -> Play -> Maybe MacroGame`
- Decide how your play is oriented: are you just taking the two indexes in 0...8, or do you need FOUR ints
- Select appropriate microgame, update with the helper function, and then rpelace it. You can use a zip-with-index approach, or `splitAt` in a case expression
```
case splitAt num miniBoards of 
       (before, board:after) -> Just $ before ++ [update board] ++ after
       _ -> Nothing
```

**Comment by pharris-trinity** [comment]
Got a working makePlay, but it's kinda ugly :( Still takes in nextPlayer as a parameter... not sure of another way to do it
